mechta/apps/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [path('', views.ViewPage.as_view(), name='page'),
               path('<slug:article_slug>/', views.ArticleView.as_view(), name='article')]

mechta/apps/forum/urls.py
# Core Django imports.
from django.urls import path

# Forum application imports.
from forum.views.content.items_views import (
    ForumView,
    SectionView,
    TopicView,
)

from forum.views.content.create_item_views import (
    CreateTopicView,
    CreateMessage,
)

from forum.views.content.stuff_views import (
    topic_handler,
    UnreadTopicView,
    SearchResult,
    ViewMembers,
)

from forum.views.account.register_views import (
    RegisterUser,
    ActivationConfirm,
    ActivateUser,
    PasswordReset,
    PasswordResetDone,
    PasswordResetConfirm,
    PasswordResetComplete,
)

from forum.views.account.login_logout_views import (
    LoginUser,
    logout_user,
)

from forum.views.user_profile.user_profile_views import (
    UserProfile,
    UserProfileUpdate,
)

# from django.conf import settings
# from django.conf.urls.static import static

# Specifies the app name for name spacing.
app_name = 'forum'


# forum/urls.py
urlpatterns = [
    # Content

    # /
    path(
        route='',
        view=ForumView.as_view(),
        name='home'
    ),

    # /section_id/
    path(
        route='<int:section_id>/',
        view=SectionView.as_view(),
        name='section'
    ),

    # /section_id/topic_id/
    path(
        route='<int:section_id>/<int:topic_id>/',
        view=TopicView.as_view(),
        name='topic'
    ),

    # /unread_topics/
    path(
        route='unread_topics/',
        view=UnreadTopicView.as_view(),
        name='unread_topics'
    ),

    # /topic-handler/   (for ajax-request)
    path(
        route='topic-handler/',
        view=topic_handler,
        name='topic-handler'
    ),

    # '/members/'
    path(
        route='members/',
        view=ViewMembers.as_view(),
        name='members'
    ),

    # /search_results/
    path(
        route='search_results/',
        view=SearchResult.as_view(),
        name='search_results'
    ),

    # /section_id/create_topic/
    path(
        route='<int:section_id>/create_topic/',
        view=CreateTopicView.as_view(),
        name='create_topic'
    ),

    # /section_id/topic_id/create_message/'
    path(
        route='<int:section_id>/<int:topic_id>/create_message/',
        view=CreateMessage.as_view(),
        name='create_message'
    ),

    # Account

    # /register/
    path(
        route='register/',
        view=RegisterUser.as_view(),
        name='register'
    ),

    # /activate/uidb64/token/
    path(
        route='activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        view=ActivateUser.as_view(),
        name='activate'
    ),

    # /activation-confirm/user_slug/
    path(
        route='activation-confirm/<slug:user_slug>/',
        view=ActivationConfirm.as_view(),
        name='activation_confirm'
    ),

    # /password-reset/'
    path(
        route='password-reset/',
        view=PasswordReset.as_view(),
        name='password_reset'
    ),

    # /password-reset/done/
    path(
        route='password-reset/done/',
        view=PasswordResetDone.as_view(),
        name='password_reset_done'
    ),

    # /password-reset-confirm/<uidb64>/<token>/
    path(
        route='password-reset-confirm/<uidb64>/<token>/',
        view=PasswordResetConfirm.as_view(),
        name='password_reset_confirm'
    ),

    # /password-reset-complete/
    path(
        route='password-reset-complete/',
        view=PasswordResetComplete.as_view(),
        name='password_reset_complete'
    ),

    # /login/
    path(
        route='login/',
        view=LoginUser.as_view(),
        name='login'
    ),

    # /logout/
    path(
        route='logout/',
        view=logout_user,
        name='logout'
    ),

    # User Profile

    # profile/user_slug/
    path(
        route='profile/<slug:user_slug>/',
        view=UserProfile.as_view(),
        name='user_profile'
    ),

    # profile/user_slug/update/
    path(
        route='profile/<slug:user_slug>/update/',
        view=UserProfileUpdate.as_view(),
        name='user_profile_update'
    ),
]

# # включаем возможность обработки картинок
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mechta/apps/website/urls.py
# Core Django imports.
from django.urls import path

# Website application imports.
from . import views

# Specifies the app name for name spacing.
app_name = 'website'

# website/urls.py
urlpatterns = [

    # /
    path(
        route='',
        view=views.HomePage.as_view(),
        name='home'
    ),

    # /search_results/
    path(
        route='search_results/',
        view=views.SearchResult.as_view(),
        name='search_results'
    ),

    # /<alias_slug>/
    path(
        route='<slug:alias_slug>/',
        view=views.Page.as_view(),
        name='page'
    ),
]

mechta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('articles/', include('articles.urls')),
    path('', include('website.urls')),
    path('debug/', include('debug_toolbar.urls')),
]

# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mechta/apps/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    slug = models.SlugField('url', max_length=255, db_index=True, unique=True, default='', blank=True)
    title = models.CharField('название новости', max_length=200)
    text = models.TextField('текст новости')
    pub_date = models.DateField('дата публикации')

    def __str__(self):
        return self.title + ' ' + str(self.pub_date)

    def get_absolute_url(self):
        host = 'http://127.0.0.1:8000/'
        return host + '/articles/' + self.slug + '/'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора', max_length=50)
    text = models.CharField('комментарий', max_length=200)

    def __str__(self):
        return self.author_name

mechta/apps/forum/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm, PasswordResetForm
from mechta.utils.image_widget import ImageWidget

class UserPasswordResetForm(SetPasswordForm):
    """Change password form."""
    new_password1 = forms.CharField(label='Новый пароль',
                                    help_text="<ul class='errorlist text-muted'><li>Your password can 't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can 't be a commonly used password.</li> <li>Your password can 't be entirely numeric.<li></ul>",
                                    max_length=100,
                                    required=True,
                                    widget=forms.PasswordInput(attrs={
                                                                        'class': 'form-control',
                                                                        'type': 'password',
                                                                        'id': 'user_password',
                                    }))

    new_password2 = forms.CharField(label='Введите новый пароль повторно',
                                    help_text=False,
                                    max_length=100,
                                    required=True,
                                    widget=forms.PasswordInput(
                                                                attrs={
                                                                    'class': 'form-control',
                                                                    'type': 'password',
                                                                    'id': 'user_password',
                                                                        }
                                    ))


class UserForgotPasswordForm(PasswordResetForm):
    """User forgot password, check via email form."""
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    # class Meta:
    #     model = User
    #     fields = ('email',)



class UserForm(UserCreationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повтор пароля',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['land_plot'].empty_label = "Участок не выбран"

    class Meta(UserCreationForm):
        model = Profile
        fields = ('phone', 'land_plot')
        labels = {'land_plot': 'Номер участка'}
        widgets = {
                    'phone': forms.TextInput(attrs={'class': 'form-control'}),
                    'land_plot': forms.Select(attrs={'class': 'form-select'})
        }

    def add_user_pk(self, pk):
        self.instance.user_id = pk


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-control'}),
                               disabled=True)
    first_name = forms.CharField(label='Имя',
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Фамилия',
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class ProfileUpdateForm(forms.ModelForm):
    phone = forms.CharField(label='Телефон',
                            widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Profile
        fields = ('phone', 'land_plot',)
        labels = {'land_plot': 'Номер участка'}
        widgets = {'land_plot': forms.Select(attrs={'class': 'form-select'})}


class AvatarUpdateForm(forms.ModelForm):
    image = forms.ImageField(label='Аватар',
                             required=False,
                             widget=ImageWidget())

    class Meta:
        model = Avatar
        fields = ('image',)


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ReplyPostForm(forms.ModelForm):
    text = forms.CharField(label='Сообщение',
                           widget=forms.Textarea(attrs={'class': 'form-control','rows': 10, 'cols': 5}))

    class Meta(UserCreationForm):
        model = Message
        fields = ('text',)

    def add_user_id(self, id_):
        self.instance.user_id = id_

    def add_topic_id(self, id_):
        self.instance.topic_id = id_


class CreateTopicForm(forms.ModelForm):
    title = forms.CharField(label='Название темы',
                            widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'cols': 10}))
    description = forms.CharField(label='Описание темы',
                                  widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'cols': 5}))

    class Meta(UserCreationForm):
        model = Topic
        fields = ('title', 'description',)

    def add_user_id(self, id_):
        self.instance.user_id = id_

    def add_section_id(self, id_):
        self.instance.section_id = id_

mechta/apps/forum/forms/create_item_forms.py
# Core Django imports.
from django import forms
from django.contrib.auth.forms import UserCreationForm

# Forum application imports.
from forum.models import *


class CreateTopicForm(forms.ModelForm):
    """
    Form for creating a new topic.
    """

    title = forms.CharField(label='Название темы',
                            widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'cols': 10}))
    description = forms.CharField(label='Описание темы',
                                  widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'cols': 5}))

    class Meta(UserCreationForm):
        model = Topic
        fields = ('title', 'description',)


class CreateMessageForm(forms.ModelForm):
    """
    Form for creating a new message.
    """

    text = forms.CharField(label='Сообщение',
                           widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'cols': 5}))

    class Meta(UserCreationForm):
        model = Message
        fields = ('text',)

mechta/apps/articles/views.py
from django.views.generic import DetailView, ListView
from mechta.apps.utils import DataMixin
from .models import *


class ViewPage(DataMixin, ListView):
    model = Article
    context_object_name = 'page'
    template_name = 'articles/articles_content.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context,
                                        )
        return context

class ArticleView(DataMixin, DetailView):
    model = Article
    context_object_name = 'page'
    template_name = 'articles/article.html'
    slug_url_kwarg = 'article_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context,
                                        )
        return context

mechta/apps/website/views.py
from django.views.generic import DetailView, ListView
from django.contrib.contenttypes.models import ContentType
from mechta.apps.utils import DataMixin
from django.db.models import Q
from .models import *

class HomePage(DataMixin, ListView):
    model = SitePage
    context_object_name = 'page'
    template_name = 'home_content.html'

    def get_queryset(self):
        return self.model.objects.get(pk=1)

    def get_context_data(self, **kwargs):

        context_model = self.object_list.context_model
        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context,
                                        context_model=context_model)
        return context


class Page(DataMixin, DetailView):

    model = SitePage
    context_object_name = 'page'
    slug_url_kwarg = 'alias_slug'
    template_name_field = 'template'


    def get_context_data(self, **kwargs):

        context_model = self.object.context_model
        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context,
                                        context_model=context_model)
        return context


class SearchResult(DataMixin, ListView):
    context_object_name = 'page'
    model = SitePage
    model_ = ContentType.objects.get(app_label='articles', model='article').model_class()
    template_name = 'website/search_results.html'
    count_qw_1 = 0

    def get_queryset(self):
        query = self.request.GET.get('w_q').strip()
        if query:
            qw_1 = self.model.objects. \
                filter(Q(title__icontains=query) |
                       Q(intro_text__icontains=query) |
                       Q(content__icontains=query)).\
                values('title', 'intro_text', 'content', 'slug')
            qw_2 = self.model_.objects. \
                filter(Q(title__icontains=query) |
                       Q(text__icontains=query)). \
                values('title', 'text', 'text', 'slug')

            self.count_qw_1 = len(qw_1)

            return qw_1.union(qw_2)
        else:
            return {}

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context)
        context['query'] = self.request.GET.get('w_q').strip()
        if context['query']:
            context['qw_1'] = self.count_qw_1
        return context

mechta/templates/forum/user_profile/profile_content.html
{% extends "main.html" %}

{% block title %} Форум {% endblock %}

{% block second_page_link %}
     <li class="breadcrumb-item">
        <a href="{% url 'forum:home' %}">Форум</a>
    </li>

    <li class="breadcrumb-item active" aria-current="page">
        Профиль: {{ page.user__username }}
    </li>

{% endblock %}

{% block content_title %}

    <h2 class="pb-2 border-bottom">
        Форум
    </h2>

{% endblock %}

{% block content %}

<div class="row row-cols-1  align-items-md-center g-8 py-8">
    {% if request.user.is_authenticated %}
    {% include "forum/user_profile/register_panel.html" %}

    <div class=" my-3 p-3 bg-body rounded shadow-sm">
        <div class="row border-bottom">
            <p> Профиль: {{ page.user__username }} , (уч.{{ page.land_plot__number }})</p>
            <div class="px-3 py-2">
                <p>Аватар:</p>
            {% if page.avatar__image_url %}
                <img class="avatar avatar-xxl" src="{{MEDIA_URL}}{{ page.avatar__image_url }}"/>
            {% else %}
                <span class="avatar avatar-xxl bg-secondary rounded-3" style="font-size:64px">
                    {{ page.user__username|slice:2|upper }}
                </span>
            {% endif %}
            </div>

            <p> Имя: {{ page.user__first_name }}</p>
            <p> Фамилия: {{ page.user__last_name }}</p>
            <p> Последнее посещение: {{ page.last_visit }}</p>
            <p> Дата регистрации: {{ page.user__date_joined }}</p>
        </div>
        <div class="row mt-2">
            <p> Статистика пользователя: </p>
        </div>
        <div class="d-flex flex-row mb-2 border-bottom">
            <div class="text-muted py-1 px-3">
                <p> Создано тем: {{ page.num_topics }}</p>
            </div>
            <div class="text-muted py-1 px-3">
                <p> Написанно сообщений: {{ page.num_messages }}</p>
            </div>
        </div>

        {% if request.user.username == page.user__username  %}
            <div class="d-flex flex-row text-muted pt-0">
                <div class="me-auto mb-3 mt-1 ">
                    <a class="btn btn-primary rounded-3" href="{% url 'forum:user_profile_update' page.slug %}"
                       role="button">Редактировать профиль</a>
                </div>
            </div>
        {% endif %}
    </div>
    {% else %}
        {% include 'forum/content/stuff/suggestion_to_register.html' %}
    {% endif %}
</div>

{% endblock %}

mechta/templates/forum/user_profile/profile_update_page.html
{% extends 'main.html' %}

{% block title %} Страница редактирования профиля {% endblock %}

{% block second_page_link %}

    <li class="breadcrumb-item">
        <a href="{% url 'forum:home' %}">Форум</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
        Страница редактирования профиля
    </li>

{% endblock %}


{% block content_title %}

    <h2 class="pb-2 border-bottom">
        Страница редактирования профиля
    </h2>

{% endblock %}


{% block content %}

<div class="container-fluid col-6">

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-error">{{ user_form.non_field_errors }}</div>
        {% for field in user_form %}
            <div class="row mb-3 align-items-center g-2">
                <label class="col-sm-2 col-form-label" for="{{ field.id_for_label }}">
                    {{field.label}}:
                </label>
                 <div class="col-sm-10">
                    {{ field }}
                 </div>
            </div>
            <div class="form-error">
                {{ field.errors }}
            </div>
        {% endfor %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for field in profile_form %}
            <div class="row mb-3 align-items-center g-2">
                <label class="col-sm-2 col-form-label" for="{{ field.id_for_label }}">
                    {{ field.label }}:
                </label>
                <div class="col-sm-10">
                    {{ field }}
                </div>
                <div class="form-error">
                    {{ field.errors }}
                </div>
            </div>
        {% endfor %}
        {% for field in avatar_form %}
            <div class="row mb-3 align-items-center g-2">
                <label class="col-sm-2 col-form-label" for="{{ field.id_for_label }}">
                    {{field.label}}:
                </label>
                 <div class="col-sm-10">
                    {{ field }}
                 </div>
            </div>
            <div class="form-error">
                {{ field.errors }}
            </div>
        {% endfor %}

        <button class="btn btn-lg btn-primary rounded-3" type="submit">Сохранить изменения</button>
    </form>
</div>

{% endblock %}

mechta/templates/forum/user_profile/register_panel.html
<div class="d-flex container-fluid navbar-expand-lg navbar-light bg-light rounded shadow-sm p-2">
    {% if request.user.is_authenticated %}
        <div class="nav-item p-2">
             <a class="nav-link" href="{% url 'forum:home' %}">Форум</a>
        </div>
        <div class="nav-item p-2">
             <a class="nav-link" href="{% url 'forum:user_profile' user.profile.slug %}">Профиль</a>
        </div>
        <div class="nav-item p-2">
             <a class="nav-link" href="{% url 'forum:members' %}">Пользователи</a>
        </div>
        <div class="nav-item p-2">
             <a class="nav-link" href="#">Подписки</a>
        </div>
        <div class="nav-item p-2 me-auto">
             <a class="nav-link" href="#">Новое на форуме</a>
        </div>


        <div class="nav-item pt-1">

            {% if user.profile.avatar.image_url %}
                <img class="avatar " src="{{MEDIA_URL}}{{ user.profile.avatar.image_url }}"/>
            {% else %}
                <span class="avatar bg-secondary rounded-3 " style="font-size:16px">
                    {{ user.username|slice:2|upper }}
                </span>
            {% endif %}
        </div>
        <div class="nav-item p-2">
            {{user.username}}
        </div>
        <div class="nav-item p-2">
            <a class="nav-link" href="{% url 'forum:logout'%}">Выйти</a>
        </div>
    {% else %}
        <div class="nav-item p-2 ms-auto">
            <a class="nav-link" href="{% url 'forum:register' %}">Регистрация</a>
        </div>
        <div class="nav-item p-2">
            <a class="nav-link" href="{% url 'forum:login' %}">Логин</a>
        </div>
    {% endif %}
        <form action="{% url 'forum:search_results' %}" method="get" >
            <input name="f_q" class="form-control rounded-3" type="text" placeholder="Поиск по форуму" aria-label="Search">
        </form>


</div>