mechta/apps/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'

urlpatterns = [path('', views.ViewPage.as_view(), name='page'),
               path('<slug:article_slug>/', views.ArticleView.as_view(), name='article')]

mechta/apps/forum/urls.py
# Core Django imports.
from django.urls import path

# Forum application imports.
from forum.views.content.items_views import (
    ForumView,
    SectionView,
    TopicView,
)

from forum.views.content.create_item_views import (
    CreateTopicView,
    CreateMessage,
)

from forum.views.content.stuff_views import (
    topic_handler,
    UnreadTopicView,
    SearchResult,
    ViewMembers,
)

from forum.views.account.register_views import (
    RegisterUser,
    ActivationConfirm,
    ActivateUser,
    PasswordReset,
    PasswordResetDone,
    PasswordResetConfirm,
    PasswordResetComplete,
)

from forum.views.account.login_logout_views import (
    LoginUser,
    logout_user,
)

from forum.views.user_profile.user_profile_views import (
    UserProfile,
    UserProfileUpdate,
)

# from django.conf import settings
# from django.conf.urls.static import static

# Specifies the app name for name spacing.
app_name = 'forum'


# forum/urls.py
urlpatterns = [
    # Content

    # /
    path(
        route='',
        view=ForumView.as_view(),
        name='home'
    ),

    # /section_id/
    path(
        route='<int:section_id>/',
        view=SectionView.as_view(),
        name='section'
    ),

    # /section_id/topic_id/
    path(
        route='<int:section_id>/<int:topic_id>/',
        view=TopicView.as_view(),
        name='topic'
    ),

    # /unread_topics/
    path(
        route='unread_topics/',
        view=UnreadTopicView.as_view(),
        name='unread_topics'
    ),

    # /topic-handler/   (for ajax-request)
    path(
        route='topic-handler/',
        view=topic_handler,
        name='topic-handler'
    ),

    # '/members/'
    path(
        route='members/',
        view=ViewMembers.as_view(),
        name='members'
    ),

    # /search_results/
    path(
        route='search_results/',
        view=SearchResult.as_view(),
        name='search_results'
    ),

    # /section_id/create_topic/
    path(
        route='<int:section_id>/create_topic/',
        view=CreateTopicView.as_view(),
        name='create_topic'
    ),

    # /section_id/topic_id/create_message/'
    path(
        route='<int:section_id>/<int:topic_id>/create_message/',
        view=CreateMessage.as_view(),
        name='create_message'
    ),

    # Account

    # /register/
    path(
        route='register/',
        view=RegisterUser.as_view(),
        name='register'
    ),

    # /activate/uidb64/token/
    path(
        route='activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/',
        view=ActivateUser.as_view(),
        name='activate'
    ),

    # /activation-confirm/user_slug/
    path(
        route='activation-confirm/<slug:user_slug>/',
        view=ActivationConfirm.as_view(),
        name='activation_confirm'
    ),

    # /password-reset/'
    path(
        route='password-reset/',
        view=PasswordReset.as_view(),
        name='password_reset'
    ),

    # /password-reset/done/
    path(
        route='password-reset/done/',
        view=PasswordResetDone.as_view(),
        name='password_reset_done'
    ),

    # /password-reset-confirm/<uidb64>/<token>/
    path(
        route='password-reset-confirm/<uidb64>/<token>/',
        view=PasswordResetConfirm.as_view(),
        name='password_reset_confirm'
    ),

    # /password-reset-complete/
    path(
        route='password-reset-complete/',
        view=PasswordResetComplete.as_view(),
        name='password_reset_complete'
    ),

    # /login/
    path(
        route='login/',
        view=LoginUser.as_view(),
        name='login'
    ),

    # /logout/
    path(
        route='logout/',
        view=logout_user,
        name='logout'
    ),

    # User Profile

    # profile/user_slug/
    path(
        route='profile/<slug:user_slug>/',
        view=UserProfile.as_view(),
        name='user_profile'
    ),

    # profile/user_slug/update/
    path(
        route='profile/<slug:user_slug>/update/',
        view=UserProfileUpdate.as_view(),
        name='user_profile_update'
    ),
]

# # включаем возможность обработки картинок
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mechta/apps/website/urls.py
# Core Django imports.
from django.urls import path

# Website application imports.
from . import views

# Specifies the app name for name spacing.
app_name = 'website'

# website/urls.py
urlpatterns = [

    # /
    path(
        route='',
        view=views.HomePage.as_view(),
        name='home'
    ),

    # /search_results/
    path(
        route='search_results/',
        view=views.SearchResult.as_view(),
        name='search_results'
    ),

    # /<alias_slug>/
    path(
        route='<slug:alias_slug>/',
        view=views.Page.as_view(),
        name='page'
    ),
]

mechta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('forum/', include('forum.urls')),
    path('articles/', include('articles.urls')),
    path('', include('website.urls')),
    path('debug/', include('debug_toolbar.urls')),
]

# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mechta/apps/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    slug = models.SlugField('url', max_length=255, db_index=True, unique=True, default='', blank=True)
    title = models.CharField('название новости', max_length=200)
    text = models.TextField('текст новости')
    pub_date = models.DateField('дата публикации')

    def __str__(self):
        return self.title + ' ' + str(self.pub_date)

    def get_absolute_url(self):
        host = 'http://127.0.0.1:8000/'
        return host + '/articles/' + self.slug + '/'

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author_name = models.CharField('имя автора', max_length=50)
    text = models.CharField('комментарий', max_length=200)

    def __str__(self):
        return self.author_name

mechta/apps/forum/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm, PasswordResetForm
from mechta.utils.image_widget import ImageWidget

class UserPasswordResetForm(SetPasswordForm):
    """Change password form."""
    new_password1 = forms.CharField(label='Новый пароль',
                                    help_text="<ul class='errorlist text-muted'><li>Your password can 't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can 't be a commonly used password.</li> <li>Your password can 't be entirely numeric.<li></ul>",
                                    max_length=100,
                                    required=True,
                                    widget=forms.PasswordInput(attrs={
                                                                        'class': 'form-control',
                                                                        'type': 'password',
                                                                        'id': 'user_password',
                                    }))

    new_password2 = forms.CharField(label='Введите новый пароль повторно',
                                    help_text=False,
                                    max_length=100,
                                    required=True,
                                    widget=forms.PasswordInput(
                                                                attrs={
                                                                    'class': 'form-control',
                                                                    'type': 'password',
                                                                    'id': 'user_password',
                                                                        }
                                    ))


class UserForgotPasswordForm(PasswordResetForm):
    """User forgot password, check via email form."""
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    # class Meta:
    #     model = User
    #     fields = ('email',)



class UserForm(UserCreationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повтор пароля',
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class ProfileForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['land_plot'].empty_label = "Участок не выбран"

    class Meta(UserCreationForm):
        model = Profile
        fields = ('phone', 'land_plot')
        labels = {'land_plot': 'Номер участка'}
        widgets = {
                    'phone': forms.TextInput(attrs={'class': 'form-control'}),
                    'land_plot': forms.Select(attrs={'class': 'form-select'})
        }

    def add_user_pk(self, pk):
        self.instance.user_id = pk


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-control'}),
                               disabled=True)
    first_name = forms.CharField(label='Имя',
                                 widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Фамилия',
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email',
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class ProfileUpdateForm(forms.ModelForm):
    phone = forms.CharField(label='Телефон',
                            widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Profile
        fields = ('phone', 'land_plot',)
        labels = {'land_plot': 'Номер участка'}
        widgets = {'land_plot': forms.Select(attrs={'class': 'form-select'})}


class AvatarUpdateForm(forms.ModelForm):
    image = forms.ImageField(label='Аватар',
                             required=False,
                             widget=ImageWidget())

    class Meta:
        model = Avatar
        fields = ('image',)


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class ReplyPostForm(forms.ModelForm):
    text = forms.CharField(label='Сообщение',
                           widget=forms.Textarea(attrs={'class': 'form-control','rows': 10, 'cols': 5}))

    class Meta(UserCreationForm):
        model = Message
        fields = ('text',)

    def add_user_id(self, id_):
        self.instance.user_id = id_

    def add_topic_id(self, id_):
        self.instance.topic_id = id_


class CreateTopicForm(forms.ModelForm):
    title = forms.CharField(label='Название темы',
                            widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'cols': 10}))
    description = forms.CharField(label='Описание темы',
                                  widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'cols': 5}))

    class Meta(UserCreationForm):
        model = Topic
        fields = ('title', 'description',)

    def add_user_id(self, id_):
        self.instance.user_id = id_

    def add_section_id(self, id_):
        self.instance.section_id = id_

mechta/apps/forum/forms/create_item_forms.py
# Core Django imports.
from django import forms
from django.contrib.auth.forms import UserCreationForm

# Forum application imports.
from forum.models import *


class CreateTopicForm(forms.ModelForm):
    """
    Form for creating a new topic.
    """

    title = forms.CharField(label='Название темы',
                            widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'cols': 10}))
    description = forms.CharField(label='Описание темы',
                                  widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3, 'cols': 5}))

    class Meta(UserCreationForm):
        model = Topic
        fields = ('title', 'description',)


class CreateMessageForm(forms.ModelForm):
    """
    Form for creating a new message.
    """

    text = forms.CharField(label='Сообщение',
                           widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 10, 'cols': 5}))

    class Meta(UserCreationForm):
        model = Message
        fields = ('text',)

mechta/apps/articles/views.py
from django.views.generic import DetailView, ListView
from mechta.apps.utils import DataMixin
from .models import *


class ViewPage(DataMixin, ListView):
    model = Article
    context_object_name = 'page'
    template_name = 'articles/articles_content.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context,
                                        )
        return context

class ArticleView(DataMixin, DetailView):
    model = Article
    context_object_name = 'page'
    template_name = 'articles/article.html'
    slug_url_kwarg = 'article_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context,
                                        )
        return context

mechta/apps/website/views.py
from django.views.generic import DetailView, ListView
from django.contrib.contenttypes.models import ContentType
from mechta.apps.utils import DataMixin
from django.db.models import Q
from .models import *

class HomePage(DataMixin, ListView):
    model = SitePage
    context_object_name = 'page'
    template_name = 'home_content.html'

    def get_queryset(self):
        return self.model.objects.get(pk=1)

    def get_context_data(self, **kwargs):

        context_model = self.object_list.context_model
        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context,
                                        context_model=context_model)
        return context


class Page(DataMixin, DetailView):

    model = SitePage
    context_object_name = 'page'
    slug_url_kwarg = 'alias_slug'
    template_name_field = 'template'


    def get_context_data(self, **kwargs):

        context_model = self.object.context_model
        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context,
                                        context_model=context_model)
        return context


class SearchResult(DataMixin, ListView):
    context_object_name = 'page'
    model = SitePage
    model_ = ContentType.objects.get(app_label='articles', model='article').model_class()
    template_name = 'website/search_results.html'
    count_qw_1 = 0

    def get_queryset(self):
        query = self.request.GET.get('w_q').strip()
        if query:
            qw_1 = self.model.objects. \
                filter(Q(title__icontains=query) |
                       Q(intro_text__icontains=query) |
                       Q(content__icontains=query)).\
                values('title', 'intro_text', 'content', 'slug')
            qw_2 = self.model_.objects. \
                filter(Q(title__icontains=query) |
                       Q(text__icontains=query)). \
                values('title', 'text', 'text', 'slug')

            self.count_qw_1 = len(qw_1)

            return qw_1.union(qw_2)
        else:
            return {}

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context = self.add_user_context(context=context)
        context['query'] = self.request.GET.get('w_q').strip()
        if context['query']:
            context['qw_1'] = self.count_qw_1
        return context

mechta/templates/forum/content/forum_search_results.html
{% extends "main.html" %}

{% block title %} Результаты поиска по форуму {% endblock %}

{% block second_page_link %}
    <li class="breadcrumb-item">
        <a href="{% url 'forum:page' %}">Форум</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
        Результаты поиска по форуму
    </li>
{% endblock %}


{% block content_title %}

    <h2 class="pb-2 border-bottom">
        Результаты поиска по форуму
    </h2>

{% endblock %}

{% block content %}

<div class="row row-cols-1  align-items-md-center g-8 py-8">

    {% include "forum/register_panel.html" %}

    <div class=" my-3 p-3 bg-body rounded shadow-sm">


    {% if request.user.is_authenticated %}
         <div class="row border-bottom">
                <div class="d-flex col-12 text-muted pt-3">
                    Поиск " {{ query }} " по форуму - найдено {{ page.count }} результатов :
                </div>
         </div>

        {% if page %}
            {% for item in page %}

            <div class="row border-bottom">
                <div class="d-flex col-12 text-muted pt-3">
    {#                <p class="pb-3 mb-0 small lh-sm">#}
    {#                    ...{{ item.topic_id__section_id__title }}...{{ item.topic_id__section_id__description }}...#}
    {#                </p>#}
    {#                <p class="pb-3 mb-0 small lh-sm">#}
    {#                    ...{{ item.topic_id__title }}...{{ item.topic_id__description }}...#}
    {#                </p>#}
    {#                <p class="pb-3 mb-0 small lh-sm">#}
    {#                    ...{{ item.text }}....#}
    {#                </p>#}
                    <a class="text-muted"
                        href="
                            {% if item.topic__id is None %}
                                {% url 'forum:section' item.id %}
                            {% else %}
                                {% url 'forum:topic' item.id item.topic__id %}
                            {% endif %}
                            ">
                        <p class="pb-3 mb-0 small lh-sm">
                            {{ forloop.counter }}.
                            ...{{ item.title|slice:":20"  }}...{{ item.description|slice:":20"  }}...
                        {% if item.topic__title %}
                                ...{{ item.topic__title|slice:":20"  }}...{{ item.topic__description|slice:":20" }}...
                        {% endif %}
                        {% if item.topic__message__text %}
                                ...{{ item.topic__message__text|slice:":30"  }}...
                        {% endif %}
                        </p>
                    </a>

                </div>
            </div>
            {% endfor %}
        {% else %}
            <div class="row border-bottom">
                <div class="d-flex col-12 text-muted pt-3">
                    <p class="pb-3 mb-0 small lh-sm">
                        К сожалению на форуме ничего не найдено.<br>
                    </p>
                </div>
            </div>
        {% endif %}

    {% else %}
        {% include "forum/suggestion_to_register.html" %}
    {% endif %}
        {% include "forum/statistic_panel.html" %}
    </div>
</div>

{% endblock %}

mechta/templates/forum/content/members_page.html
{% extends "main.html" %}

{% block title %} Форум {% endblock %}

{% block second_page_link %}
     <li class="breadcrumb-item">
        <a href="{% url 'forum:page' %}">Форум</a>
    </li>

    <li class="breadcrumb-item active" aria-current="page">
        Пользователи
    </li>

{% endblock %}

{% block content_title %}

    <h2 class="pb-2 border-bottom">
        Форум
    </h2>

{% endblock %}

{% block content %}

<div class="row row-cols-1  align-items-md-center g-8 py-8">
    {% if request.user.is_authenticated %}
    {% include "forum/register_panel.html" %}

    <div class=" my-3 p-3 bg-body rounded shadow-sm">
        <div class="row border-bottom">
            <div class="d-flex col-3 text-muted pt-3 justify-content-center">
                <h6 class=" pb-2 mb-0">Пользователь</h6>
            </div>
            <div class="d-flex col-1 text-muted pt-3 justify-content-center">
                <h6 class="pb-2 mb-0">Права</h6>
            </div>
            <div class="d-flex col-5 text-muted pt-3 justify-content-center">
                <h6 class="pb-2 mb-0">Кол-во сообщений</h6>
            </div>
            <div class="d-flex col-3 text-muted pt-3 justify-content-center">
                <h6 class="pb-2 mb-0">Последний визит</h6>
            </div>
        </div>



        {% for item in page %}
            <div class="row border-bottom">
                <div class="d-flex col-3 justify-content-start">
                    <div class="p-1">
                    {% if item.profile__avatar__image_url %}
                        <img class="avatar" src="{{ MEDIA_URL }}{{ item.profile__avatar__image_url }}"/>
                    {% else %}
                        <span class="avatar bg-secondary rounded-3" style="font-size:16px">
                            {{ item.username|slice:2|upper }}
                        </span>
                    {% endif %}
                    </div>
                    <div class="pt-3">
                        <a class="nav-link" href="{% url 'forum:user_profile' item.profile__slug  %}">
                            <p class="pb-3 mb-0 small lh-sm" >
                                {{ item.username }}, ( участок {{ item.profile__land_plot__number }})<br>
                            </p>
                        </a>
                    </div>
                </div>
                <div class="d-flex col-1 text-muted pt-3 justify-content-center">
                    <p class="pb-3 mb-0 small lh-sm">
                        {{ item.is_member }}
                    </p>
                </div>
                <div class="d-flex col-5 text-muted pt-3 justify-content-center">
                    <p class="pb-3 mb-0 small lh-sm">
                        {{ item.num_messages }}
                    </p>
                </div>
                <div class="d-flex col-3 text-muted pt-3 justify-content-center">
                    <p class="pb-3 mb-0 small lh-sm">
                        {{ item.profile__last_visit }}
                    </p>
                </div>
            </div>
        {% endfor %}

    </div>
    {% else %}
        {% include 'forum/suggestion_to_register.html' %}
    {% endif %}
</div>

{% endblock %}

mechta/templates/forum/content/section_content.html
{% extends "main.html" %}

{% block title %}

    {% for item in section %}
        {{ item.title }}
    {% endfor %}

{% endblock %}

{% block second_page_link %}

    <li class="breadcrumb-item">
        <a href="{% url 'forum:page' %}">Форум</a>
    </li>

    {% for item in section %}

    <li class="breadcrumb-item active" aria-current="page">
        Раздел: {{ item.title }}
    </li>

    {% endfor %}

{% endblock %}


{% block content_title %}

    <h2 class="pb-2 border-bottom">
        Форум
    </h2>

{% endblock %}


{% block content %}

<div class="row row-cols-1  align-items-md-center g-8 py-8">

    {% include "forum/register_panel.html" %}

    <div class=" my-3 p-3 bg-body rounded shadow-sm">

    {% if request.user.is_authenticated %}

        <div class="d-flex flex-md-row flex-nowrap border-bottom">
            {% for item in section %}
            <div class="w-10 align-self-center">
                <span class="px-3">
                    <i class="fa-solid {{ item.icon }} fa-xl" style="color:#f1c232"></i>
                </span>
            </div>
            <div class="flex-fill w-60 text-muted my-1">
                <h6 class="mb-1">Название раздела:  <strong>{{ item.title }}.</strong></h6>
                <p class="text-gray-dark mb-0"> Описание раздела: {{ item.description }}</p>
            </div>
            {% endfor %}
            <div class="flex w-30 text-muted align-self-center">
                <div class="px-5">
                    <a class="btn btn-primary rounded-3" href="{% url 'forum:create_topic' view.kwargs.section_id %}"
                       role="button">Создать новую тему</a>
                </div>
            </div>
        </div>

        <div class="row border-bottom">
            <div class="d-flex col-8 text-muted pt-3">
                <h6 class=" pb-2 mb-0">Название темы</h6>
            </div>
            <div class="d-flex col-4 text-muted  pt-3">
                <h6 class="pb-2 mb-0">Кол-во сообщений</h6>
            </div>

        </div>

        {% if page %}

            {% for item in page %}
            <div class="row border-bottom">
                <div class="d-flex col-8 text-muted pt-3">

                    <span class="px-3 mt-2">
                        <i class="fa-regular fa-pen-to-square fa-xl" style="color:#f1c232"></i>
                    </span>

                    <p class="pb-3 mb-0 small lh-sm">
                        <a class="nav-link" href="{% url 'forum:topic' item.section_id item.id %}">
                            <strong class="d-block text-gray-dark"> {{ item.title }} </strong>
                        </a>
                        {{ item.description }}<br>
                    </p>
                </div>
                <div class="d-flex col-4 text-muted  pt-3">
                    <p class="pb-3 mb-0 small lh-sm">
                        {{ item.num_messages }}
                    </p>
                </div>
            </div>
            {% endfor %}


        {% else %}

            <div class="row border-bottom">
                <div class="d-flex col-12 text-muted pt-3">
                    <span class="px-3 mt-2">
                        <i class="fa-regular fa-square fa-xl" style="color:#f1c232"></i>
                    </span>
                    <p class="mt-3 small lh-sm">
                        Пока нет тем. Будьте первым
                    </p>
                </div>

            </div>

        {% endif %}



        {% include "forum/statistic_panel.html" %}

    {% else %}

        {% include 'forum/suggestion_to_register.html' %}

    {% endif %}


    </div>
</div>

{% endblock %}

mechta/templates/forum/content/unread_topics.html
{% extends "main.html" %}

{% block title %}
    Непрочитанные темы
{% endblock %}

{% block second_page_link %}

    <li class="breadcrumb-item">
        <a href="{% url 'forum:page' %}">Форум</a>
    </li>
    <li class="breadcrumb-item active" aria-current="page">
        Непрочитанные темы
    </li>

{% endblock %}


{% block content_title %}

    <h2 class="pb-2 border-bottom">
        Форум
    </h2>

{% endblock %}


{% block content %}

<div class="row row-cols-1  align-items-md-center g-8 py-8">

    {% include "forum/register_panel.html" %}

    <div class=" my-3 p-3 bg-body rounded shadow-sm">

    {% if request.user.is_authenticated %}
        {% if page %}
            <div class="row border-bottom">
                <div class="d-flex col-6 text-muted pt-3">
                    <h6 class=" pb-2 mb-0">Название темы</h6>
                </div>
                <div class="d-flex col-3 text-muted pt-3 justify-content-center">
                    <h6 class=" pb-2 mb-0">Кол-во сообщений</h6>
                </div>
                <div class="d-flex col-3 text-muted pt-3 justify-content-center">
                    <h6 class="pb-2 mb-0">Прочитанно</h6>
                </div>

            </div>
            {% for item in page %}
            <div class="row border-bottom" data-row-id="{{ item.topic_id }}">
                <div class="d-flex col-6 text-muted pt-3">

                    <span class="px-3 mt-2">
                        <i class="fa-regular fa-pen-to-square fa-xl" style="color:#f1c232"></i>
                    </span>

                    <p class="pb-3 mb-0 small lh-sm">
                        <a class="nav-link" href="{% url 'forum:topic' item.topic__section_id item.topic_id %}">
                            <strong class="d-block text-gray-dark"> {{ item.topic__title }} </strong>
                        </a>
                        {{ item.topic__description }}<br>
                    </p>
                </div>
                <div class="d-flex col-3 text-muted pt-3 justify-content-center">
                     <p class="pb-3 mb-0 small lh-sm">
                         {{ item.num_messages }}
                     </p>
                </div>
                <div class="d-flex col-3 text-muted pt-3 justify-content-center">
                    <input class="form-check-input mt-0 message_box check-input" action="{% url 'forum:topic-handler' %}" type="checkbox" name="is_read" data-id="{{ item.topic_id }}" >
                </div>
            </div>
            {% endfor %}

        {% include "forum/filter_panel.html" %}
        {% else %}
            <p class="p-3 ">
                У Вас нет непрочитанных тем.
            </p>
        {% endif %}

        {% include "forum/statistic_panel.html" %}

    {% else %}

        {% include 'forum/suggestion_to_register.html' %}

    {% endif %}


    </div>
</div>

{% endblock %}